defaultSemverRangePrefix: ""
enableColors: true
enableConstraintsChecks: true
enableInlineBuilds: true
enableTelemetry: false
nodeLinker: node-modules
tsEnableAutoTypes: true
yarnPath: .yarn/releases/yarn-4.5.1-git.20241025.hash-f59bbf9-code-chronicles-patch.cjs
# TODO: patch Yarn to not add extra newlines to this file
