defaultSemverRangePrefix: ""
enableColors: true
enableConstraintsChecks: true
enableInlineBuilds: true
enableTelemetry: false
nodeLinker: node-modules
tsEnableAutoTypes: true
yarnPath: .yarn/releases/yarn-4.5.1-patched.cjs
