defaultSemverRangePrefix: ""
enableColors: true
enableConstraintsChecks: true
enableInlineBuilds: true
enableTelemetry: false
nodeLinker: node-modules
tsEnableAutoTypes: true
yarnPath: .yarn/releases/yarn-4.5.1-git.20241018.hash-031b5da-code-chronicles-patch.cjs
