// THIS FILE IS GENERATED! DO NOT MODIFY IT MANUALLY!!
// Instead, update the generation process or inputs and run `yarn codegen`.

import { z } from "zod";

import { getGraphQLClient } from "../../getGraphQLClient.ts";
import type * as Types from "../../graphqlTypes.generated.ts";

type QuestionListQueryVariables = Types.Exact<{
  categorySlug: Types.Scalars["String"]["input"];
  limit?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  skip?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  filters: Types.QuestionListFilterInput;
}>;

type QuestionListQuery = {
  questionList: {
    totalNum: number;
    data: Array<{
      difficulty: string;
      isPaidOnly: boolean;
      questionFrontendId: string;
      title: string;
      titleSlug: string;
      challengeQuestionsV2: Array<{ date: string }>;
    }>;
  };
};

export const QUERY =
  "query($categorySlug:String!,$limit:Int,$skip:Int,$filters:QuestionListFilterInput!){questionList(categorySlug:$categorySlug limit:$limit skip:$skip filters:$filters){data{challengeQuestionsV2{date}difficulty isPaidOnly questionFrontendId title titleSlug}totalNum}}";

export const queryResultZodType = z.object({
  questionList: z.object({
    data: z.array(
      z.object({
        challengeQuestionsV2: z.array(z.object({ date: z.string() })),
        difficulty: z.string(),
        isPaidOnly: z.boolean(),
        questionFrontendId: z.string(),
        title: z.string(),
        titleSlug: z.string(),
      }),
    ),
    totalNum: z.number().int().nonnegative(),
  }),
});

export type QueryResult = z.infer<typeof queryResultZodType>;
export type QueryVariables = QuestionListQueryVariables;

export async function fetchGraphQL(
  variables: QueryVariables,
): Promise<QueryResult> {
  const untrustedData = await getGraphQLClient().request(QUERY, variables);

  // The type annotation serves as a TypeScript assert that the generated
  // Zod type is compatible with the types generated by GraphQL Codegen.
  const validatedData: QuestionListQuery & QueryResult =
    queryResultZodType.parse(untrustedData);

  return validatedData;
}
