name: Check formatting on PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up everything
        uses: ./.github/workflows/set-up-everything

      - name: Check formatting
        run: yarn format
