name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# Cancel runs in progress as well, since the latest one likely supersedes previous ones.
concurrency:
  group: deploy-github-pages
  cancel-in-progress: true

jobs:
  deploy-github-pages:
    environment:
      name: deploy-github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          # For some reason Node 22 was causing some problems with installing dependencies.
          node-version: 20
          cache: yarn
          cache-dependency-path: tools/yarn.lock

      - name: Install dependencies
        # I learned about https://github.com/yarnpkg/yarn/issues/2739 painfully.
        run: (cd tools && yarn install --production=false --frozen-lockfile)

      - name: Build app
        run: (cd tools/adventure-pack && yarn build-app)
        env:
          NODE_ENV: production

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./tools/adventure-pack/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
