name: Lint PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up everything
        uses: ./.github/workflows/set-up-everything

      - name: Linting
        run: yarn lint
        # TODO: Annotations of files that fail lint?
        # TODO: Maybe write up a job summary per https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
