name: Run tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-tests:
    name: Node ${{ matrix.node-version }}

    strategy:
      fail-fast: false
      matrix:
        node-version:
          # This is the version used by LeetCode.
          - 20.10.0
          - lts
          - latest

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up everything
        uses: ./.github/workflows/set-up-everything

      # Yarn constraints are kinda like tests.
      - name: Check Yarn constraints
        run: yarn constraints
        # TODO: Maybe write up a job summary per https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

      - name: Run tests
        run: yarn test
        # TODO: Annotations of test files that fail?
        # TODO: Maybe write up a job summary per https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
